# Generated by Django 6.1.1 on 2026-10-06 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_savecourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='required_watch_percent',
            field=models.PositiveIntegerField(default=90, verbose_name='Phần trăm cần học để hoàn thành'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='unlock_delay_hours',
            field=models.PositiveIntegerField(default=0, verbose_name='Thời gian chờ (giờ)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='unlock_type',
            field=models.CharField(choices=[('SEQUENTIAL', 'Học xong bài trước'), ('TIME_DELAY', 'Mở sau thời gian')], default='SEQUENTIAL', max_length=20, verbose_name='Cách mở bài'),
        ),
        migrations.CreateModel(
            name='UserStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LearningActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('minutes', models.PositiveIntegerField(default=0)),
                ('lessons_completed', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_user_learning_date')],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_seconds', models.PositiveIntegerField(default=0)),
                ('watched_percent', models.FloatField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='app.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'lesson'), name='unique_user_lesson_progress')],
            },
        ),
    ]
